### ISSUE TITLE
Change `main` of `package.json` to point to `react-calendar.js`

### ISSUE THREAD

**Issue by andru** [freiksenet/react-calendar#22]
Is there a good use case for the `main` property of `package.json` to be set to a file in the `dist` directory? 
When working with webpack it's better to have uncompiled modules where possible.

I just hit this an issue with the current value by doing an `npm install` direct from this repo instead of npm, which errors out because there's no `dist` dir.  Installing direct from a git repo is a valid use case to stay on the bleeding edge rather than wait for npm releases, but right now this is broken (without manually building after every update)

Unless there's any loaders going on which are incompatible with standard node `require` then setting `main` to `./react-calendar.js` should work great for both `node` and `webpack`.

**Comment by freiksenet** [comment]
This would mean that users of the library would have to transpile this library, I am not 100% sure that's the best way.

There is at least jsx in the code, which would break on standard node require.

Maybe I should push a separate branch to npm that would point to dist and point to ./react-calendar otherwise.

**Comment by lolJS** [comment]
Closed by #28.
